### PR TITLE
feat: enable google ads

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
<details>
<summary>looooong image</summary>

image

</details>

This is a lot. Is this how the layout should be?

**Comment by scissorsneedfoodtoo** [comment]
Thanks for checking this out, @nhcarrigan. 

That's really interesting -- not sure why all the ads are showing up at the bottom of the article there. That sidebar  should be hidden on narrower screens, with just a large ad at the bottom above the footer.

It might have something to do with the check for the ads enabled flag in the `.env` file, or the logic in the script that checks whether or not you're signed into freeCodeCamp.

Here's what they should look like (though without the red color):

thumb-Clipboard - October 27, 2021 4_01 PM

thumb-Clipboard - October 26, 2021 6_00 PM

Currently it shows two ads in the sidebar by default, and adds another ad for every 2 minutes of reading time, which we get form the Ghost API.

This can be tweaked, but it seems like a decent starting point for now.

In your screenshot above, is that with 11ty pulling in some of the default Ghost articles? I may need to add those back in for more testing.

**Comment by naomi-lgbt** [comment]
Yes that's correct. The only content I have locally is the default Ghost articles.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks for confirming that.

Not sure if it was a recent update or not, but it seems like the sidebar does show up at the bottom of the article now, even when authenticated. Fortunately the fix is pretty simple, and just needed another line of CSS.

Hopefully it works now!

**Comment by naomi-lgbt** [comment]
image

Just to confirm before approving, ALL users (even authenticated) should see the footer ad yes?

**Comment by scissorsneedfoodtoo** [comment]
Thanks for pointing that out too, @nhcarrigan. That's a silly oversight on my part :facepalm: I'll push up a quick change for that now.

We may eventually have special sponsored ads similar to CSS Tricks that we'll want to show at all times. But we should hide all Google ads for authenticated readers.

**Comment by scissorsneedfoodtoo** [comment]
Okay, hopefully that's everything! Now unauthenticated readers should see a sidebar and bottom banner ad on screens <= 900px, and just the bottom banner ad on screens < 900px.

Authenticated readers shouldn't see any Google ads, and the layout should be the same as we have in the current Ghost News theme.

Also, I've converted this into a draft for now so we can keep the main branch clean, and test Google ads with separate test deploys before merging.

**Review by naomi-lgbt — COMMENTED** [review]
Alright this is looking good to me.

When logged in, I see 0 ads. When logged out, I see the bottom ad always, and the sidebar ads if my screen is big enough.

A quick question - authenticated users will only be our authors, right? A standard reader doesn't have a way to authenticate with Ghost.

**Comment by raisedadead** [comment]
> A quick question - authenticated users will only be our authors, right? A standard reader doesn't have a way to authenticate with Ghost.

Nope, authenticated users will be users of the `/learn` platform. We have an interesting way to check for people signed in on the main platform.

**Comment by naomi-lgbt** [comment]
Oh cool!

Think this is good to go then.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks again for your thorough testing @nhcarrigan.

I did a bit more testing to ensure that the `ADS_ENABLED` environment variable works, just in case we need to disable ads globally.

It may have been better to add a label to this rather than reverting it to a draft. I believe this is ready to go, though it may be good to do a test deploy and ensure the ads load / Google Adsense is configure correctly from the dashboard before merging.

**Review by naomi-lgbt — DISMISSED** [review]
I think this is good to go

**Review by naomi-lgbt — DISMISSED** [review]
All of the logic still seems to work. No ads when authenticated, all ads when not authenticated. Sidebar ads don't render on smaller screens.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
