### PR TITLE
chore(i18n): processed translations

### PR DESCRIPTION
**Pull request by camperbot**
This PR was opened auto-magically by Crowdin.

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@naomi-lgbt, could you take a look at this when you get a chance? For some reason this PR is creating a new `Bengali` directory in `config/i18n/locales` rather than using the existing `bengali` directory.

Does this have something to do with the changes in https://github.com/freeCodeCamp/news/pull/546?

Or do we need to make some updates to https://github.com/freeCodeCamp/crowdin-action as well?

**Comment by naomi-lgbt** [comment]
This is actually a config that I need to set on Crowdin itself - I'll hit this in the morning.

**Review by naomi-lgbt — APPROVED** [review]
@scissorsneedfoodtoo this should be accurate now?

**Review by RafaelDavisH — CHANGES_REQUESTED** [review]
@scissorsneedfoodtoo 

Correct me if I am wrong, but I believe line 54-55 should be update to only be:

```json
    "details": {
    - "original-article": "{{ <0> }}Original article:{{ </0> }} {{ title }} by {{ author }}",
    "original-article": "{{ <0> }}Original article:{{ </0> }} {{ title }}",
    - "translated-by": "{{ <0> }}Translated by:{{ </0> }} {{ translator }}"
    },

```

To prevent redundancy on the author/ translator, something that i18n brought up especially in mobile view.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thank you for your help with that @naomi-lgbt. The path looks right now.

And thanks for catching that @RafaelDavisH. Now that https://github.com/freeCodeCamp/news/pull/549 is in, it should be fine to merge the changes in this PR. As far as I can tell, the Bengali publication isn't using the original author / translator feature anyway.

We can get these changes in now, and the rest of the file should get synced with the English one the next time the Crowdin Actions run.

**Review by RafaelDavisH — APPROVED** [review]
That's great - let's go 🚀

**Pull request closed without merging**
