### PR TITLE
feat: enable Ukrainian builds

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Like #427, this is split into two parts: https://github.com/freeCodeCamp/news/pull/427#issue-1379419082

### CODE REVIEW

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo actually you want to drop [0dd2f9e](https://github.com/freeCodeCamp/news/pull/432/commits/0dd2f9e7e73fb8b2e45ea9eea0bdffdfdff85529) and add it afterwords.

Here is the order that needs to be followed:

1. Enable only the `build` stage for a language - this is done correctly in [c75cf5f](https://github.com/freeCodeCamp/news/pull/432/commits/c75cf5f557c27ed00efed219e4f9ae5f39c7581e)
2. Run the workflow manually with the PR branch selected. This will build a first image we can use and pushes it to the Azure Container Registry.
3. Go Azure Portal and create a Web App for Containers on the existing Azure App Service Plan, for this first image. Optionally - Do additional steps to map domains, etc. 
4. Return to the PR and enable the deploy stage for the language - that is [0dd2f9e](https://github.com/freeCodeCamp/news/pull/432/commits/0dd2f9e7e73fb8b2e45ea9eea0bdffdfdff85529) and add it afterwords.
5. Merge the PR and profit in the next run.

I will improve this messy flow soon when we move to nomad.

**Comment by scissorsneedfoodtoo** [comment]
Ah, thanks for those details @raisedadead.

Sure, I'll drop https://github.com/freeCodeCamp/news/pull/432/commits/0dd2f9e7e73fb8b2e45ea9eea0bdffdfdff85529 and follow those steps. I'm not sure if I know how to do everything on Azure, but I can reach out in chat if anything.

For now, I'll drop that commit and run the build manually with this branch selected, then add it back in.

**Comment by scissorsneedfoodtoo** [comment]
Just to consolidate updates in one area, I was able to create the App Service for prod / org Ukrainian News images in Azure under freecodecamp-news-org-ukrainian.

The only think I wasn't able to do was add a custom domain, ukrainian.news.cdn.freecodecamp.org. I believe that's because NGINX hasn't been updated yet, though I can't say for sure.

**Comment by raisedadead** [comment]
See: https://staff-wiki.freecodecamp.org/docs/flight-manuals/azure/create-asp-webapp-containers and related documentation. I will improve those docs as I go. Hopefully we would not need them soon * wink *.

**Comment by raisedadead** [comment]
You can now add the other commit and land this when you are happy.

**Review by raisedadead — APPROVED** [review]

**Pull request merged**
