### PR TITLE
fix hash links in articles

### LINKED ISSUE #528: Extra Scroll padding for linked section
**Describe the feature**
When you visit a linked section like this https://www.freecodecamp.org/news/developer-news-style-guide#headlines-the-only-part-of-your-tutorial-that-100-of-people-will-read, you will face a missing section of the heading.

Screenshot_2022-12-28-18-04-35-27_e4424258c8b8649f6e67d283a50a2cbc

-----

We can use `scroll-padding-top`  to set offset for this, here is the link for it

https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-top

### PR DESCRIPTION
**Pull request by jcubic**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #528

### CODE REVIEW

**Review by scissorsneedfoodtoo — COMMENTED** [review]
Hi @jcubic, thanks for your patience, and for submitting this fix.

I did some for different localizations and things look much better than before. However, the banner still covers up a bit of the text in the mobile iPhone 5 view, where the banner can have a height of about 64px in some cases. I think if we just bump up the last value to `0.75em` that should allow enough spacing between the banner and the top of the heading text on smaller screens without the gap looking too big on larger screens.

We could also target all headings from h1-h6, which can be used on Ghost or Hashnode if someone uses markdown to write.

Replacing lines 857 - 861 with something like this could work:

```css
.post-full-content h1:target,
.post-full-content h2:target,
.post-full-content h3:target,
.post-full-content h4:target,
.post-full-content h5:target,
.post-full-content h6:target {
  scroll-margin-top: calc(
    var(--header-height) + 44px + 0.75em
  ); /* 44px height of the banner */
}
```

**Comment by jcubic** [comment]
Update the code.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks for your quick updates with that, @jcubic.

The tricky thing about this repo is that, because we have some secrets to do builds for our e2e tests, branches should be pushed to the upstream repo here so those can run.

I'll open up a new PR using your commits so the tests pass, then will merge in these changes.

**Comment by scissorsneedfoodtoo** [comment]
Everything here LGTM 👍 

Closing in favor of https://github.com/freeCodeCamp/news/pull/1024

**Pull request closed without merging**
