### PR TITLE
feat: add shouldCanonicalHaveGAM filter

### PR DESCRIPTION
**Pull request by ahmaxed**
Checklist:

This pr replaces the GAM test url with a more flexible filter.
This function will be used to gradually roll out the GAM script.

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by ojeytonwilliams** [comment]
@ahmaxed I've no clue why the tests are failing. It looks unrelated, but I can't pretend to understand why.

**Comment by ahmaxed** [comment]
Thanks for the review. There has been some changes after the Hashnode migration. Kris is looking into the tests.

**Review by scissorsneedfoodtoo — APPROVED** [review]
Tested locally and everything LGTM 👍 

Thanks again for your patience with those tests.

**Pull request merged**
