### PR TITLE
fix: finalize redirects

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Addresses #70 and #71.

This preps the locales for release, and uses Dothraki to mimic some of the legacy locales for English News (though the destination URLs go to `/dothraki/news/...` rather than `/news/...` like the will for the English release).

### CODE REVIEW

**Review by ojeytonwilliams — COMMENTED** [review]
Just one silly question!  Why don't we need redirects for the italian any more?

**Comment by scissorsneedfoodtoo** [comment]
Hey! Thanks for taking a look at this.

And sorry for the force push. I remembered late last night that Chinese News is on a subdomain, so the path should be `/news/...` instead of `/lang/news/...` like with the other languages.

About the redirects for Italian News, I don't think they're necessary. English News has those redirects due to legacy Medium links, and I wanted to get some early testing in. Since the publications for the other languages didn't exist before Ghost, they should only need the rewrite for the RSS feeds.

Also, the Chinese publication has just one redirect for an article that was published and shared with the incorrect slug.

**Review by ojeytonwilliams — APPROVED** [review]
Thanks for the explanation, Kris.  This all LGTM :+1:

**Comment by ShaunSHamilton** [comment]
My silly question time!

Why do these not get the 302 redirect type, anymore?

**Comment by raisedadead** [comment]
> Why do these not get the 302 redirect type, anymore?

Because they are implicit. See: https://github.com/vercel/serve-handler#options

**Pull request merged**
