### PR TITLE
refactor(scripts): tests in TypeScript

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

I updated the Cypress tests to use Typescript. There should be no errors or any other technical issues resulting from this PR.

### CODE REVIEW

**Comment by raisedadead** [comment]
Thanks for the PR. 

Just a quick tip: In future keep the branch names conventional ex: `feat-my-feature` or `fix/my-bug` - that is dashes and slashes are fine but other chars aren't because they will break someone else's tooling. I believe you were mixing up [conventional commits](conventionalcommits.org/en/v1.0.0) with branch naming.

You do not need to change anything for this PR.

**Review by raisedadead — CHANGES_REQUESTED** [review]
Do we not need the TypeScript package?

**Comment by a2937** [comment]
We do. I forgot to update the packages.

**Comment by raisedadead** [comment]
Sorry - do you mind resolving the conflicts?

**Comment by a2937** [comment]
I'm going to rebase it soon.

**Comment by a2937** [comment]
I seem to have made a mistake while trying to rebase.  I'll open a new PR and try again.

**Pull request closed without merging**
