### PR TITLE
fix: sitemaps

### LINKED ISSUE #438: Sitemaps Not Getting Fetched During Build
Sitemaps aren't fetched reliably during the build process.

Here are some examples from English News:

- Index: https://www.freecodecamp.org/news/sitemap.xml
- Pages: https://www.freecodecamp.org/news/sitemap-pages.xml
- Posts: https://www.freecodecamp.org/news/sitemap-posts.xml
- Authors: https://www.freecodecamp.org/news/sitemap-authors.xml
- Tags: https://www.freecodecamp.org/news/sitemap-tags.xml

The index page is empty, and should look similar to this:

image

Looking at the posts sitemap, it seems like it hasn't been updated since we switched over to JAMstack.

I believe the reason we still have sitemaps for pages, posts, authors, and tags is that they were previously available through the Ghost served site. But for newer sites like Ukrainian, which was never available as a Ghost served site, the sitemap is completely empty.

We have most of the data we need to build the sitemaps during the build. However, some things like the timestamp when a tag or author profile was updated isn't available through the Ghost API.

It seems like the best we can do is build the sitemaps using whatever data we have available, and to omit the "Last Modified" / `<lastmod>` date for tag and author profile pages.

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes https://github.com/freeCodeCamp/news/issues/438

This PR fixes the sitemap index page, and the individual pages, posts, authors, and tags sitemaps. It also adds a new test to both parse and validate the sitemaps based on index and individual sitemap schemas.

As mentioned in the issue above, it's not possible to get the latest updated date for tags and authors from the Ghost API, so those need to be left blank.

Otherwise, the date for each of the sitemaps here should match the sitemaps coming from Ghost as closely as possible.

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, a new package is being installed, `libxmljs`, which is probably why the Socket Security test is failing.

But I'm not entirely sure why Test (16.x) shows `Expected — Waiting for status to be reported`. Is there something that need to be done in `node.js-test.yml`?

**Comment by raisedadead** [comment]
> Is there something that need to be done in node.js-test.yml?

Try a rebase against main.

**Comment by raisedadead** [comment]
> the Socket Security test is failing.

That's OK and normal when adding new packages. The failing status is more of a "warning" to us that a new package is getting added - and the reviewer should check for potential malice.

So we are in the clear here.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks for confirming that.

I was able to fix the issue the the Node test that failed to report, though I had to create another script to build one of the CI sites to generate the sitemaps 🤦 

In the future I'll look into simplifying the scripts in `package-lock.json` and the way the builds and dev servers are handled. It feels like there are too many scripts and Node arguments that would be better in a `.env` file or GH Action environment variables.

**Review by raisedadead — DISMISSED** [review]

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo 

I have rebased this for resolving conflicts with the lock file. Sorry had to squash the commits to make it easier. 

Can you do a quick sanity check if it's in order? I will merge this soon.

**Comment by scissorsneedfoodtoo** [comment]
No worries. Thanks for taking care of the merge conflicts and for squashing all of those messy commits.

Sure thing. I'll take another look at everything today and will @ mention you if everything looks good to go.

**Comment by scissorsneedfoodtoo** [comment]
Thanks again for your help with everything @raisedadead.

Just did some test builds and checked all the different sitemaps, and everything should be good to go. The data seems consistent with what we had before, except for the missing `lastmod` dates for tags and authors because we don't have access to that info through the Ghost API.

**Comment by raisedadead** [comment]
> we don't have access to that info through the Ghost API.

Do you mean the content API; maybe the admin API has that info? IDK - just thinking our loud. Either way, I think it is not a big deal.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, that's true. I double checked the admin API and it does seem to offer that info for authors and tags.

The tags endpoint is still marked as experimental in their admin docs, but it should be similar enough to the content API.

We could look at using the admin API to source all the content in the future. But we would just have to be extra careful not to expose those.

Like you said, I'm not sure it's such a bit deal for the tags and author pages — it seems more important to have `lastmod` / `updated_at` dates for posts and pages.

I'll see if there's a way to monitor Google Search Console for info about this, and if missing `lastmod` dates for tag and author pages end up hurting us.

**Comment by raisedadead** [comment]
Correct. 

I think we would need to move this repo to private if we wanted to use the admin API. Was worth discussing, though.

BTW, I see that there seem to be some issues with the sitemap on the Google Search Console. Now I am not sure if it was before or after this PR. Do you want to check it?

**Comment by scissorsneedfoodtoo** [comment]
Sure thing, I'll check it out now.

Also, I'll see if there's something else we can use besides `lastmod` for those sitemaps. Maybe `changefreq` and `priority`?

**Pull request merged**
