### PR TITLE
feat: footer march 2022

### PR DESCRIPTION
**Pull request by ahmaxed**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This one is also the footer update for the forum: https://github.com/freeCodeCamp/forum-theme/pull/62

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Comment by ojeytonwilliams** [comment]
Given the yaml/json shenanigans, https://github.com/freeCodeCamp/forum-theme/pull/67, could we convert one or the other so that we can just copy/paste?

**Comment by ShaunSHamilton** [comment]
> could we convert one or the other so that we can just copy/paste?

Sounds too sensible.

**Comment by raisedadead** [comment]
> so that we can just copy/paste?

Or we put them up in a single location like the CDN, and reference them? I bet, we could do some smart engineering workarounds.

**Comment by ojeytonwilliams** [comment]
> Or we put them up in a single location like the CDN, and reference them? I bet, we could do some smart engineering workarounds.

Or both!  Yaml would work in both platforms and we could store that in the CDN.

**Comment by scissorsneedfoodtoo** [comment]
Just getting caught up on everything now, and I think that's a good idea. I remember Niraj mentioning something similar a little while back, and we're definitely at the point where that makes sense.

I'll create an issue and put some quick thoughts there for more discussion and tracking.

**Review by scissorsneedfoodtoo — APPROVED** [review]
Tested locally and everything LGTM.

I don't think we'll be able to merge this until the tests pass. But since the PR is coming from @ahmadabdolsaheb's repo, the CI builds won't work due to the missing API keys from the Dockerized Ghost containers.

Probably the easiest thing to do would be to push these changes to upstream and create a new PR. Alternatively, @ahmadabdolsaheb could add the correct keys to his fork manually, or with Doppler if we want to preserve these reviews.

**Comment by raisedadead** [comment]
> Probably the easiest thing to do would be to push these changes to upstream and create a new PR.

Yes - It was intentional that forks do not have the ability to run CI jobs via PRs. That is a contribution to this particular repo that needs to come from this very repo.

**Comment by scissorsneedfoodtoo** [comment]
Closed in favor of #223.

**Pull request closed without merging**
